dashboard:
  states:
    - component: main
      capability: temperatureMeasurement
      version: 1
      idx: 0
      group: main
      values: []
      composite: false
  actions:
    - component: main
      capability: momentary
      version: 1
      idx: 0
      group: main
      values: []
      composite: false
  basicPlus: []
detailView:
  - component: main
    capability: temperatureMeasurement
    version: 1
    values: []
    patch: []
  - component: main
    capability: relativeHumidityMeasurement
    version: 1
    values: []
    patch: []
  - component: main
    capability: momentary
    version: 1
    values: []
    patch: []
automation:
  conditions:
    - component: main
      capability: temperatureMeasurement
      version: 1
      values: []
      patch: []
      exclusion: []
    - component: main
      capability: relativeHumidityMeasurement
      version: 1
      values: []
      patch: []
      exclusion: []
  actions:
    - component: main
      capability: momentary
      version: 1
      values: []
      patch: []
      exclusion: []
type: profile
